// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maui
{
	public partial class SearchViewController : UIViewController
	{
		public SearchViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            InvokeOnMainThread(() => {
                View.BackgroundColor = UIColor.FromRGB(40, 47, 68);
                //UIImageView.Animate(animHeart.AnimationDuration, new Action(animHeart.StartAnimating));
            });
        }
    }
}
